baseURL = 'https://doc.ulutasalperen.com/'
title = 'Alperen Doc'
theme = 'hugo-book'

# Required for mermaid and katex shortcodes
[markup.goldmark.renderer]
unsafe = true

[params]
# Temayı kalıcı olarak koyu yapmak için:
BookTheme = "dark"
